from neomodel import StringProperty, RelationshipTo, RelationshipFrom, JSONProperty
from trm_api.graph_models.generates_event import GeneratesEventRel
from .base import BaseNode

class Event(BaseNode):
    """
    Represents an Event in the TRM-OS ontology.
    An event is an immutable record of something that has happened.
    """
    # Core properties
    # e.g., 'TensionDetected', 'TaskCompleted', 'UserJoinedTeam'
    event_type = StringProperty(required=True, index=True)

    # The data associated with the event, stored in a flexible JSON format
    payload = JSONProperty()

    # --- Relationships ---
    # An event is triggered by a user or an agent.
    triggered_by = RelationshipTo('BaseNode', 'TRIGGERED_BY') # User or Agent

    # An event often relates to a specific entity.
    context = RelationshipTo('BaseNode', 'RELATES_TO')
    
    # An event can be generated by projects, tasks or agents
    generated_by_projects = RelationshipFrom('trm_api.graph_models.project.Project', 'GENERATES_EVENT', model=GeneratesEventRel)
    generated_by_tasks = RelationshipFrom('trm_api.graph_models.task.Task', 'GENERATES_EVENT', model=GeneratesEventRel)
    generated_by_agents = RelationshipFrom('trm_api.graph_models.agent.Agent', 'GENERATES_EVENT', model=GeneratesEventRel)

    def __str__(self):
        return f"{self.event_type} (UID: {self.uid})"
