import pytest
import uuid
from unittest.mock import Mock, patch, MagicMock, AsyncMock
from datetime import datetime

from trm_api.models.relationships import Relationship, RelationshipType, TargetEntityTypeEnum
from trm_api.services.relationship_service import RelationshipService


class TestGeneratesKnowledgeRelationship:
    """Unit tests for the GENERATES_KNOWLEDGE relationship service methods."""
    
    def setup_method(self):
        """Set up test fixtures before each test method."""
        self.service = RelationshipService()
        
        # Sample IDs for testing
        self.win_id = str(uuid.uuid4())
        self.snippet_id = str(uuid.uuid4())
        
        # Sample relationship data
        self.sample_relationship = {
            "source_id": self.win_id,
            "source_type": "Win",
            "target_id": self.snippet_id,
            "target_type": "KnowledgeSnippet",
            "type": "GENERATES_KNOWLEDGE",
            "createdAt": datetime.utcnow()
        }
    
    @pytest.mark.asyncio
    @patch('trm_api.services.relationship_service.RelationshipService._get_db')
    async def test_create_generates_knowledge_relationship(self, mock_get_db):
        """Test creating a GENERATES_KNOWLEDGE relationship."""
        # Mock setup
        mock_session = MagicMock()
        mock_tx = MagicMock()
        mock_result = MagicMock()
        mock_record = MagicMock()
        
        mock_record.__getitem__.side_effect = lambda key: self.sample_relationship.get(key)
        mock_result.single.return_value = mock_record
        mock_tx.run.return_value = mock_result
        
        # Cấu hình mock để hỗ trợ async context manager
        mock_session.execute_write = AsyncMock(return_value=Relationship(**self.sample_relationship))
        mock_session_ctx = MagicMock()
        mock_session_ctx.__aenter__ = AsyncMock(return_value=mock_session)
        mock_session_ctx.__aexit__ = AsyncMock(return_value=None)
        mock_db = MagicMock()
        mock_db.session.return_value = mock_session_ctx
        # Biến _get_db thành AsyncMock để có thể sử dụng với await
        mock_get_db.side_effect = AsyncMock(return_value=mock_db)
        
        # Execute test
        result = await self.service.create_relationship(
            source_id=self.win_id,
            source_type=TargetEntityTypeEnum.WIN,
            target_id=self.snippet_id,
            target_type=TargetEntityTypeEnum.KNOWLEDGE_SNIPPET,
            relationship_type="GENERATES_KNOWLEDGE"
        )
        
        # Assertions
        assert result is not None
        assert result.source_id == self.win_id
        assert result.source_type == "Win"
        assert result.target_id == self.snippet_id
        assert result.target_type == "KnowledgeSnippet"
        assert result.type == "GENERATES_KNOWLEDGE"
        
        # Verify mock was called correctly
        mock_session.execute_write.assert_called_once()
    
    @pytest.mark.asyncio
    @patch('trm_api.services.relationship_service.RelationshipService._get_db')
    async def test_get_knowledge_snippets_by_win(self, mock_get_db):
        """Test getting knowledge snippets generated by a WIN."""
        # Mock setup
        mock_session = MagicMock()
        mock_relationships = [Relationship(**self.sample_relationship)]
        
        # Cấu hình mock để hỗ trợ async context manager
        mock_session.read_transaction = AsyncMock(return_value=mock_relationships)
        mock_session_ctx = MagicMock()
        mock_session_ctx.__aenter__ = AsyncMock(return_value=mock_session)
        mock_session_ctx.__aexit__ = AsyncMock(return_value=None)
        mock_db = MagicMock()
        mock_db.session.return_value = mock_session_ctx
        # Biến _get_db thành AsyncMock để có thể sử dụng với await
        mock_get_db.side_effect = AsyncMock(return_value=mock_db)
        
        # Execute test
        results = await self.service.get_relationships(
            entity_id=self.win_id,
            entity_type=TargetEntityTypeEnum.WIN,
            direction="outgoing",
            relationship_type="GENERATES_KNOWLEDGE",
            related_entity_type=TargetEntityTypeEnum.KNOWLEDGE_SNIPPET
        )
        
        # Assertions
        assert len(results) == 1
        assert results[0].source_id == self.win_id
        assert results[0].target_id == self.snippet_id
        assert results[0].type == "GENERATES_KNOWLEDGE"
        
        # Verify mock was called correctly
        mock_session.read_transaction.assert_called_once()
    
    @pytest.mark.asyncio
    @patch('trm_api.services.relationship_service.RelationshipService._get_db')
    async def test_get_wins_by_knowledge_snippet(self, mock_get_db):
        """Test getting WINs that generate a specific knowledge snippet."""
        # Mock setup
        mock_session = MagicMock()
        mock_relationships = [Relationship(**self.sample_relationship)]
        
        # Cấu hình mock để hỗ trợ async context manager
        mock_session.read_transaction = AsyncMock(return_value=mock_relationships)
        mock_session_ctx = MagicMock()
        mock_session_ctx.__aenter__ = AsyncMock(return_value=mock_session)
        mock_session_ctx.__aexit__ = AsyncMock(return_value=None)
        mock_db = MagicMock()
        mock_db.session.return_value = mock_session_ctx
        # Biến _get_db thành AsyncMock để có thể sử dụng với await
        mock_get_db.side_effect = AsyncMock(return_value=mock_db)
        
        # Execute test
        results = await self.service.get_relationships(
            entity_id=self.snippet_id,
            entity_type=TargetEntityTypeEnum.KNOWLEDGE_SNIPPET,
            direction="incoming",
            relationship_type="GENERATES_KNOWLEDGE",
            related_entity_type=TargetEntityTypeEnum.WIN
        )
        
        # Assertions
        assert len(results) == 1
        assert results[0].source_id == self.win_id
        assert results[0].target_id == self.snippet_id
        assert results[0].type == "GENERATES_KNOWLEDGE"
        
        # Verify mock was called correctly
        mock_session.read_transaction.assert_called_once()
    
    @pytest.mark.asyncio
    @patch('trm_api.services.relationship_service.RelationshipService._get_db')
    async def test_delete_generates_knowledge_relationship(self, mock_get_db):
        """Test deleting a GENERATES_KNOWLEDGE relationship."""
        # Mock setup
        mock_session = MagicMock()
        mock_summary = MagicMock()
        mock_summary.counters.relationships_deleted = 1
        
        mock_result = MagicMock()
        mock_result.consume.return_value = mock_summary
        
        mock_tx = MagicMock()
        mock_tx.run.return_value = mock_result
        
        # Cấu hình mock để hỗ trợ async context manager
        mock_session.execute_write = AsyncMock(return_value=True)
        mock_session_ctx = MagicMock()
        mock_session_ctx.__aenter__ = AsyncMock(return_value=mock_session)
        mock_session_ctx.__aexit__ = AsyncMock(return_value=None)
        mock_db = MagicMock()
        mock_db.session.return_value = mock_session_ctx
        # Biến _get_db thành AsyncMock để có thể sử dụng với await
        mock_get_db.side_effect = AsyncMock(return_value=mock_db)
        
        # Execute test
        result = await self.service.delete_relationship(
            source_id=self.win_id,
            source_type=TargetEntityTypeEnum.WIN,
            target_id=self.snippet_id,
            target_type=TargetEntityTypeEnum.KNOWLEDGE_SNIPPET,
            relationship_type="GENERATES_KNOWLEDGE"
        )
        
        # Assertions
        assert result is True
        
        # Verify mock was called correctly
        mock_session.execute_write.assert_called_once()
    
    @pytest.mark.asyncio
    @patch('trm_api.services.relationship_service.RelationshipService._get_db')
    async def test_delete_generates_knowledge_relationship_not_found(self, mock_get_db):
        """Test deleting a non-existent GENERATES_KNOWLEDGE relationship."""
        # Mock setup
        mock_session = MagicMock()
        mock_summary = MagicMock()
        mock_summary.counters.relationships_deleted = 0
        
        mock_result = MagicMock()
        mock_result.consume.return_value = mock_summary
        
        mock_tx = MagicMock()
        mock_tx.run.return_value = mock_result
        
        # Cấu hình mock để hỗ trợ async context manager
        mock_session.execute_write = AsyncMock(return_value=False)
        mock_session_ctx = MagicMock()
        mock_session_ctx.__aenter__ = AsyncMock(return_value=mock_session)
        mock_session_ctx.__aexit__ = AsyncMock(return_value=None)
        mock_db = MagicMock()
        mock_db.session.return_value = mock_session_ctx
        # Biến _get_db thành AsyncMock để có thể sử dụng với await
        mock_get_db.side_effect = AsyncMock(return_value=mock_db)
        
        # Execute test
        result = await self.service.delete_relationship(
            source_id=self.win_id,
            source_type=TargetEntityTypeEnum.WIN,
            target_id=self.snippet_id,
            target_type=TargetEntityTypeEnum.KNOWLEDGE_SNIPPET,
            relationship_type="GENERATES_KNOWLEDGE"
        )
        
        # Assertions
        assert result is False
        
        # Verify mock was called correctly
        mock_session.execute_write.assert_called_once()
